# top level configuration
name = "poc"
type = "webpack"
route = "dev.cloudiphy.com/*"
vars = { ENVIRONMENT = "dev" }

[vars]
API_TOKEN = "example_dev_token"


[env.staging]
name = "poc-staging"
vars = { ENVIRONMENT = "staging" }
route = "staging.cloudiphy.com/*"

[env.production]
name = "poc-prod"
vars = { ENVIRONMENT = "production" }
routes = [
  "cloudiphy.com/foo/*",
  "cloudiphy.com/bar/*"
]
