# top level configuration
name = "poc"
type = "webpack"
route = "dev.cloudiphy.com/*"
zone_id = = "001b34a2cddc65e5740c4706d9b52da3"


[vars]
API_TOKEN = "example_dev_token"
ENVIRONMENT = "dev"

[env.staging]
name = "poc-staging"
vars = { ENVIRONMENT = "staging" }
route = "staging.cloudiphy.com/*"

[env.production]
name = "poc-prod"
vars = { ENVIRONMENT = "production" }
routes = [
  "cloudiphy.com/foo/*",
  "cloudiphy.com/bar/*"
]
