# top level configuration
name = "poc"
type = "webpack"

[vars]
API_TOKEN = "example_dev_token"
ENVIRONMENT = "dev"

[env.staging]
name = "poc-staging"
vars = { ENVIRONMENT = "staging" }
route = "staging.cloudiphy.com/*"
zone_id = "001b34a2cddc65e5740c4706d9b52da3"

[env.production]
name = "poc-prod"
vars = { ENVIRONMENT = "production" }
routes = ["https://cloudiphy.com/foo/*","https://cloudiphy.com/*"]
zone_id = "001b34a2cddc65e5740c4706d9b52da3"
